src/products/urls.py
from django.urls import path
from .views import *
app_name = 'product'
urlpatterns = [
    path('home/', home, name='home'),
    path('customer/', cus_list, name='cus-list'),
    path('customer/<int:id>/', print_cus_info, name='cus-info'),
    path('history/', order_history, name='order-history'),
    path('history/<int:id>', print_order),
    path('order/<int:id>/', create_order, name='create-order'),
    path('order/<int:id>/confirm/', check_order, name='check-order'),
    path('place/', place_list, name='place-list'),
    path('place/<int:id>/', get_cus_info, name='get-cusinfo'),
    path('place/confirm/', confirm_reserve),
    path('place/reservation/', reservation),
    path('pay/', pay),
    path('pay/fetch/', pay_fetch),
    path('pay/confirm/', pay_confirm),
    path('pay/feedback/', feedback),
    path('pay/feedback/confirm/', feedback_confirm),
    path('login/', login),
    path('login/fetch/', login_fetch),
    path('logout/', logout),
]

src/web/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings
from products import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('product/', include('products.urls')),
    path('', views.login),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
# from datetime import datetime
from django.utils import timezone
import pytz


class Pos:
    orde = ''

    @staticmethod
    def login(username, password):
        return StaffDB.check(username, password)

    @staticmethod
    def order(id_cus, id_place, note, list_food):
        for food in list_food:
            if not FoodDB.check_available(food['id'], food['size'], food['num']):
                return Food.objects.get(id=food['id']).name
        OrderDB.create_order(id_cus=id_cus, id_place=id_place,
                             note=note)
        order = Order.objects.all().last()
        for food in list_food:
            food_id = Food.objects.get(id=food['id'])
            Food_Order.objects.create(
                id_food=food_id, id_order=order, size=food['size'], quantity=food['num'])
            FoodDB.update_food(food_id, food['size'], food['num'])
        OrderDB.update_order(order, order.get_order_price())
        return True

    @staticmethod
    def place_manage():
        return PlaceDB.show_place()

    @staticmethod
    def check_reserved():
        return Place.objects.filter(status=2)

    @staticmethod
    def take_place(id_place):
        PlaceDB.update_place(id_place, True)

    @staticmethod
    def cus_list():
        return CustomerDB.get_cus_list()

    @staticmethod
    def cus_info(id):
        return CustomerDB.get_cus_info(id)

    @staticmethod
    def order_history():
        return OrderDB.get_order_history()

    @staticmethod
    def print_order(id_order):
        return OrderDB.get_order_info(id_order, True)

    @classmethod
    def pay(cls, phone):
        cus = Customer.objects.get(phone=phone)
        cls.orde = Order.objects.filter(id_cus=cus)
        cls.orde = cls.orde[cls.orde.count()-1]
        return cls.orde.get_order_item(), cus

    @classmethod
    def confirm_pay(cls):
        PlaceDB.update_place(cls.orde.id_place.id, False)
        OrderDB.update_order(cls.orde, 0)
        cls.orde.id_cus.update_cus(cls.orde.get_order_price())

    @classmethod
    def feedback(cls, eval, comt):
        FeedbackDB.create_feedback(cls.orde, eval, comt)


class CustomerDB:
    @staticmethod
    def get_cus_list():
        return Customer.objects.all()

    @staticmethod
    def get_cus_info(id):
        return Customer.objects.get(id=id)


class Customer(models.Model):

    name = models.CharField(max_length=10)
    phone = models.IntegerField(unique=True, blank=False, null=False)
    email = models.CharField(
        db_column='Email', max_length=20, blank=True, null=True)

    level = models.CharField(
        db_column='Level', max_length=8, blank=True, default='Đồng')

    totalorder = models.IntegerField(
        db_column='TotalOrder', blank=True, default=0)

    totalpay = models.IntegerField(db_column='TotalPay', blank=True, default=0)

    def update_cus(self, price):
        self.totalorder += 1
        self.totalpay += price
        if self.totalpay > 5000:
            self.level = 'Vàng'
        elif self.totalpay > 2000:
            self.level = 'Bạc'
        super().save()


class FeedbackDB:
    @staticmethod
    def create_feedback(order, eval, comt):
        Feedback.objects.create(id_order=order, evaluate=eval, comment=comt)


class Feedback(models.Model):

    id_order = models.OneToOneField(
        'Order', on_delete=models.CASCADE, unique=True)

    evaluate = models.IntegerField(blank=False, null=False)

    comment = models.CharField(
        db_column='Comment', max_length=20, blank=True, null=True)


class FoodDB:
    @staticmethod
    def check_available(id_food, size, num):
        return Food.objects.get(id=id_food).available(size, num)

    @staticmethod
    def update_food(food_id, size, quantity):
        food_id.update(size, quantity)


class Food(models.Model):

    name = models.CharField(db_column='Name', unique=True,
                            max_length=10, blank=False, null=False)

    num_size = models.IntegerField(db_column='Num_Size', blank=True, default=1)

    remain = models.FloatField(default=100)

    price = models.IntegerField(db_column='Price', blank=False, null=False)
    image = models.ImageField(null=True, blank=True)

    def available(self, size, quantity):
        if size*quantity > self.remain:
            return False
        return True

    def update(self, size, quantity):
        self.remain = self.remain-size*quantity
        super().save()


class Food_Order(models.Model):

    id_food = models.ForeignKey(Food, on_delete=models.CASCADE)

    id_order = models.ForeignKey('Order', on_delete=models.CASCADE)

    size = models.IntegerField(blank=True, default=1)

    quantity = models.IntegerField(blank=True, default=1)

    class Meta:
        unique_together = (('id_food', 'id_order'),)

    @property
    def get_price(self):
        return Food.objects.get(id=self.id_food.id).price*self.size*self.quantity


class OrderDB:
    @staticmethod
    def create_order(id_cus, id_place, note):
        cus = Customer.objects.get(id=id_cus)
        place = Place.objects.get(id=id_place)
        Order.objects.create(id_cus=cus, id_place=place, note=note)

    @staticmethod
    def get_order_history():
        return Order.objects.all()

    @staticmethod
    def get_order_info(id_order, a: bool):
        return Order.objects.get(id=id_order)

    @staticmethod
    def update_order(order, price):
        order.update(price)


class Order(models.Model):

    id_cus = models.ForeignKey(Customer, on_delete=models.CASCADE)

    id_place = models.ForeignKey(
        'Place', on_delete=models.CASCADE, related_name='order')

    starttime = models.DateTimeField(blank=True, auto_now_add=True)

    endtime = models.DateTimeField(blank=True, null=True)

    note = models.CharField(max_length=20, blank=True, null=True)

    status = models.IntegerField(blank=True, default=0)

    totalprice = models.IntegerField(blank=True, default=0)

    def update(self, price):
        if price != 0:
            self.totalprice += price
        else:
            self.status = 1
            self.endtime = timezone.now()
        super().save()

    def get_order_price(self):
        a = Food_Order.objects.filter(id_order=self)
        price = 0
        for i in a:
            price += i.get_price
        return price

    def get_order_item(self):
        return Food_Order.objects.filter(id_order=self)


class PlaceDB:
    @staticmethod
    def show_place():
        return Place.objects.all()

    @staticmethod
    def update_place(id_place, a: bool):
        Place.objects.get(id=id_place).update(a)


class Place(models.Model):

    status = models.IntegerField(blank=True, default=0)
    reserve = models.OneToOneField(
        Customer, blank=True, null=True, on_delete=models.CASCADE)

    def update(self, a: bool):
        if not a:
            self.status = 0
            self.reserve = None
        else:
            self.status = 1
        super().save()

src/products/views.py
import django.contrib.auth
from django.views.decorators.csrf import csrf_protect
from django.shortcuts import render, redirect
from .models import *
from django.urls import reverse
from django.forms.models import model_to_dict
from django.http import JsonResponse
from django.core import serializers
from django.contrib.auth import authenticate
from django.http import HttpResponse
# Create your views here.
cus = ''
place = ''


def home(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    return render(request, "t/home.html", {})


def cus_list(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    rec = Pos.cus_list()
    context = {"cus_list": rec, 'type': 106}
    return render(request, "t/Customer.html", context)


def print_cus_info(request, id):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    rec = Customer.objects.get(id=id)
    context = {"item": rec, 'type': 106}
    return render(request, "t/Customer Info.html", context)


def order_history(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    context = {"type": 103, "order_history": Pos.order_history()}
    return render(request, "t/Order.html", context)


def print_order(request, id):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    a = Pos.print_order(id)
    context = {"type": 301, "order": a,
               "items": a.get_order_item(), "order_history": Pos.order_history()}
    return render(request, "t/Order.html", context)


def place_list(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    rec = Pos.place_manage()
    context = {"place": rec}
    return render(request, "t/Table.html", context)


def reservation(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    rec = Pos.check_reserved()
    context = {"reservation": rec, "id_order": Order.objects.count()+1}
    return render(request, "t/Reservation.html", context)


def get_cus_info(request, id):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    if request.method == "POST":
        cus_name = request.POST.get('name')
        cus_phone = request.POST.get('phone')
        cus_email = request.POST.get('email')
        global cus, place
        try:
            cus = Customer.objects.get(phone=cus_phone)
        except:
            cus = Customer.objects.create(
                name=cus_name, phone=cus_phone, email=cus_email)
        place = id
        Pos.take_place(id)
        cus = model_to_dict(cus)['id']
        print(cus)
        return redirect("product:create-order", id=Order.objects.count()+1)
    return render(request, "t/Input Customer.html", {})


def create_order(request, id):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    category = {}
    category['main_food'] = Food.objects.all()[0:8]
    category['drink'] = Food.objects.all()[8:16]
    category['fast_food'] = Food.objects.all()[16:24]
    context = {"food_list": category, 'id_order': id, 'type': 101}
    return render(request, "t/Menu.html", context)


def check_order(request, id):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    import json
    a = json.loads(request.body)
    global cus, place
    try:
        print(cus, place)
        x = Pos.order(cus, place, '', a)
        return JsonResponse(True, safe=False) if x == True else JsonResponse(x, safe=False)
    except:
        return JsonResponse(False, safe=False)


def confirm_reserve(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    import json
    a = json.loads(request.body)
    global cus, place
    cus = Customer.objects.get(phone=a['id_cus'])
    cus = model_to_dict(cus)['id']
    place = a['id_place']
    Pos.take_place(place)
    return JsonResponse(True, safe=False)


def pay(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    return render(request, "t/Checkout.html", {})


def pay_fetch(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    import json
    a = json.loads(request.body)
    phone = a['phone']
    order, cus_pay = Pos.pay(phone)
    food = Food.objects.all()
    price = Pos.orde.get_order_price()
    qs_json = {}
    qs_json['cus'] = serializers.serialize('json', [cus_pay, ])
    qs_json['order'] = serializers.serialize('json', order)
    qs_json['food'] = serializers.serialize('json', food)
    return JsonResponse(qs_json, safe=False)


def pay_confirm(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    Pos.confirm_pay()
    return JsonResponse(None, safe=False)


def feedback(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    return render(request, "t/Feedback.html", {})


def feedback_confirm(request):
    if not request.user.is_authenticated:
        return render(request, "t/Login.html", {})
    import json
    a = json.loads(request.body)
    Pos.feedback(a['eval'], a['comt'])
    return JsonResponse(None, safe=False)


def login(request):
    if request.user.is_authenticated:
        return render(request, "t/home.html", {})
    return render(request, "t/Login.html", {})


def login_fetch(request):
    import json
    a = json.loads(request.body)
    userss = authenticate(username=a['user'], password=a['password'])
    if userss is not None:
        django.contrib.auth.login(request, userss)
        return JsonResponse(True, safe=False)
    else:
        return JsonResponse(False, safe=False)


def logout(request):
    django.contrib.auth.logout(request)
    return render(request, "t/Login.html", {})

src/products/templates/t/Customer Info.html
{% extends 't/main.html' %}
{% load static %}
{% block content %}
<div class="main-content" style="display: block" id="105">
    <div class="ngang">
        <table class="content-table">
            <thead>
                <tr>
                    <th>
                        <center>ID</center>
                    </th>
                    <th>
                        <center>Name</center>
                    </th>
                    <th>
                        <center>Phone number</center>
                    </th>
                    <th>
                        <center>Email</center>
                    </th>
                    <th>
                        <center>Level</center>
                    </th>
                    <th>
                        <center>Total Order</center>
                    </th>
                    <th>
                        <center>Total Pay</center>
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>
                        <center>{{ item.id }}</center>
                    </td>
                    <td>
                        <center>{{ item.name }}</center>
                    </td>
                    <td>
                        <center>{{ item.phone }}</center>
                    </td>
                    <td>
                        <center>{{ item.email }}</center>
                    </td>
                    <td>
                        <center>{{ item.level }}</center>
                    </td>
                    <td>
                        <center>{{ item.totalorder }}</center>
                    </td>
                    <td>
                        <center>${{ item.totalpay }}</center>
                    </td>
                </tr>
            </tbody>
        </table>
    </div>
    <center><a style="text-decoration: none" class="check" href="../">Quay lại</a></center>
</div>

{% endblock content %}

src/products/templates/t/Customer.html
{% extends 't/main.html' %}
{% load static %}
{% block content %}
<div class="main-content" style="display: block" id="105">
    <div class="ngang">
        <table class="content-table">
            <h3>
                <center>Customer List</center>
            </h3>
            <thead>
                <tr>
                    <th>
                        <center>ID</center>
                    </th>
                    <th>
                        <center>Name</center>
                    </th>
                    <th>
                        <center>Phone number</center>
                    </th>
                    <th>
                        <center>Email</center>
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for item in cus_list %}
                <tr>
                    <td>
                        <center>{{ item.id }}</center>
                    </td>
                    <td>
                        <center>{{ item.name }}</center>
                    </td>
                    <td>
                        <center>{{ item.phone }}</center>
                    </td>
                    <td>
                        <center>{{ item.email }}</center>
                    </td>
                    <td><a style="text-decoration: none" class="check" href="./{{ item.id }}">Check</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

src/products/templates/t/login.html
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'images/Ico.ico' %}">
    <title>POS Restaurants</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

</head>

<body>
    <!-- partial:index.partial.html -->
    <div class="login-page">
        <div class="form">
            <div class="login-form" >
                <input type="text" autocomplete="off" id='user' placeholder="username" />
                <input type="password" autocomplete="off" id='password' placeholder="password" />
                <button onclick="log()">Login</button>
            </div>
        </div>
    </div>
    <!-- partial -->
    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
    <script src="{% static 'js/jss.js' %}"></script>
    <script>
        function log() {
            var csrftoken = getCookie('csrftoken');
            var url = '/product/login/fetch/';
            console.log('lol');
            fetch(url, {
                method: 'POST',
                headers: {
                    'X-CSRFToken': csrftoken,
                },
                body: JSON.stringify({ user: document.getElementById('user').value, password: document.getElementById('password').value })
            }).then(res => {
                return res.json();
            }
            ).then((data) => {
                if (data == false) alert('Wrong password!!!');
                else location.assign("{% url 'product:home' %}");
            })
        }
    </script>
</body>

</html>

src/products/templates/t/menu.html
{% extends 't/main.html' %}
{% load static %}
{% block content %}

<div class="main-content" style="display: block" id="101">

    <div id="menu">
        <!-- PRODUCT SECTION ---------------------------------------- -->

        <section class="productionSection section" id="shop">
            <div class="thumbnail-slider" data-thumbnail-slider="true">
                <div class="thumbnail-slider-viewport-wrapper">
                    <div class="thumbnail-slider-viewport">
                        <div class="thumbnail-slider-list">
                            <a href="#Menu/FastFood" data-title="Fast food" onclick="menucate(1001)">
                                <span>
                                    <img src="{% static 'Images/fastfood.jfif' %}">
                                </span>
                            </a>
                            <a href="#Menu/Drinks" data-title="Drinks" onclick="menucate(1002)">
                                <span>
                                    <img src="{% static 'Images/drinks.jpg' %}">
                                </span>
                            </a>
                            <a href="#Menu/Main-dishes" data-title="Main dishes" onclick="menucate(1003)">
                                <span>
                                    <img src="{% static 'Images/veges.jfif' %}">
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div id="1001">
                <div class="sectionIntro">
                    <div class="headerInfo container">
                        <h2 class="title">Fast food</h2>
                    </div>
                </div>
                <div class="boxesContainer container">
                    {% for item in food_list.fast_food %}
                    <div class="boxContent">
                        <div class="boxImgDiv">
                            <img height="175.6" src="{{item.image.url}}" alt="Food Image" class="boxImg">
                        </div>
                        <div class="imgDesc">
                            <span class="imageTitle">{{item.name}}</span>
                        </div>

                        <span class="imageTitle">
                            {{item.num_size}} Size
                        </span>
                        <span class="boxImgPrice">
                            ${{item.price}}
                        </span>
                        <div class="boxImgBtn">
                            <button
                                onclick="add_cart('{{item.id}}','{{item.image.url}}','{{item.name}}','{{item.num_size}}','{{item.price}}')"
                                type="button" class="addToCartBtn"><i class='bx bxs-cart'></i>ADD TO
                                CART</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div id="1002" style="display: none">
                <div class="sectionIntro">
                    <div class="headerInfo container">
                        <h2 class="title">Drinks</h2>
                    </div>
                </div>
                <div class="boxesContainer container">
                    {% for item in food_list.drink %}
                    <div class="boxContent">
                        <div class="boxImgDiv">
                            <img height="175.6" src="{{item.image.url}}" alt="Food Image" class="boxImg">
                        </div>
                        <div class="imgDesc">
                            <span class="imageTitle">{{item.name}}</span>
                        </div>

                        <span class="imageTitle">
                            {{item.num_size}} Size
                        </span>
                        <span class="boxImgPrice">
                            ${{item.price}}
                        </span>
                        <div class="boxImgBtn">
                            <button
                                onclick="add_cart('{{item.id}}','{{item.image.url}}','{{item.name}}','{{item.num_size}}','{{item.price}}')"
                                type="button" class="addToCartBtn"><i class='bx bxs-cart'></i>ADD TO
                                CART</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div id="1003" style="display: none">
                <div class="sectionIntro">
                    <div class="headerInfo container">
                        <h2 class="title">Main dishes</h2>
                    </div>
                </div>
                <div class="boxesContainer container">
                    {% for item in food_list.main_food %}
                    <div class="boxContent">
                        <div class="boxImgDiv">
                            <img height="175.6" src="{{item.image.url}}" alt="Food Image" class="boxImg">
                        </div>
                        <div class="imgDesc">
                            <span class="imageTitle">{{item.name}}</span>
                        </div>

                        <span class="imageTitle">
                            {{item.num_size}} Size
                        </span>
                        <span class="boxImgPrice">
                            ${{item.price}}
                        </span>
                        <div class="boxImgBtn">
                            <button
                                onclick="add_cart('{{item.id}}','{{item.image.url}}','{{item.name}}','{{item.num_size}}','{{item.price}}')"
                                type="button" class="addToCartBtn"><i class='bx bxs-cart'></i>ADD TO
                                CART</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </section>
    </div>
    <!-- CART SECTION ---------------------------------------- -->
    <div id="cart">
        <section class="cartSection">
            <div class="sectionIntro">
                <div class="headerInfo container">
                    <h2 class="title">Cart</h2>
                </div>
            </div>
            <section class="middleSection " id='phuoc'>
                <section class="calcSection ">
                    <div class="btn">
                        <button onclick="confirm_order('{{id_order}}')" type="button">Add new orders</button>
                    </div>
                </section>
            </section>
        </section>

        <!--END CART-->
    </div>
</div>
<script>
    var orders = [];
    function add_cart(id, img, name, num_size, price) {
        orders.push({ id: id, num: 1, size: 1 });
        var idx = orders.length - 1;
        var a = document.createElement("div");
        document.getElementById('phuoc').appendChild(a);
        a.classList.add('firstSide');
        var b = document.createElement("img");
        b.src = img;
        var i = document.createElement("div");
        i.classList.add('imgDivv');
        i.style = "display:block";
        a.append(b, i)
        var c = document.createElement("div");
        c.classList.add('topSide');
        var d = document.createElement("span");
        d.classList.add('itemName');
        d.innerHTML = name;
        var e = document.createElement("span");
        e.classList.add('closeIcon', 'bx', 'bx-x', 'icon');
        e.innerHTML = 'x';

        e.addEventListener(
            'click',
            () => {
                orders.splice(idx, idx + 1);
                a.remove();
            },
            false
        );
        e.style.cursor = "pointer";
        var $Osc = {
            hover: function (event) {
                event.target.style.color = 'rgb(0, 188, 126)';
            },
            out: function (event) {
                event.target.style.color = "black";
            }

        }
        e.addEventListener("mouseover", $Osc.hover, false);
        e.addEventListener("mouseout", $Osc.out, false);

        c.append(d, e);
        // var f = document.createElement("span");
        // f.classList.add('itemGram');
        var f = document.createElement("label");
        f.for = 'size';
        f.innerHTML = 'Size: ';
        var f1 = document.createElement("select");
        // f1.id = 'size';

        var f2 = document.createElement("option");
        f2.value = 1;
        f2.innerHTML = 'Small';
        var f3 = document.createElement("option");
        f3.value = 2;
        f3.innerHTML = 'Normal';
        var f4 = document.createElement("option");
        f4.value = 3;
        f4.innerHTML = 'Big';
        f1.appendChild(f2)
        if (num_size == 2)
            f1.appendChild(f3)
        else if (num_size == 3)
            f1.append(f3, f4)

        var g = document.createElement("div");
        g.classList.add('bottomSide');
        i.append(c, f, f1, g)
        var h = document.createElement("div");
        h.classList.add('itemPrice');
        h.innerHTML = '$' + price;
        f1.addEventListener(
            'change',
            function () {
                orders[idx].size = Number(f1.value);
                h.innerHTML = '$' + orders[idx].num * price * orders[idx].size;
            },
            false
        );
        var k = document.createElement("div");
        k.classList.add('controls');
        g.append(h, k)
        var l = document.createElement("span");
        l.classList.add('count');
        l.innerHTML = 1;
        var m = document.createElement("span");
        m.classList.add('minusIcon');
        m.addEventListener("click", function () {
            if (orders[idx].num > 1)
                orders[idx].num -= 1;
            l.innerHTML = orders[idx].num;
            h.innerHTML = '$' + orders[idx].num * price * orders[idx].size;
        });
        var n = document.createElement("span");
        n.classList.add('plusIcon');
        n.addEventListener("click", function () {
            orders[idx].num += 1;
            l.innerHTML = orders[idx].num;
            h.innerHTML = '$' + orders[idx].num * price * orders[idx].size;
        });
        m.innerHTML = '-';
        n.innerHTML = '+';
        k.append(m, l, n);
        console.log(orders)
    }
    var csrftoken = getCookie('csrftoken');
    function confirm_order(id) {
        var url = '/product/order/' + id + '/confirm/';
        fetch(url, {
            method: 'POST',
            headers: {
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify(orders)
        }).then(res => {
            return res.json();
        }
        ).then((data) => {
            if (data == true) {
                alert("Success order!!!")
                window.location.href = "{% url 'product:place-list' %}";
            }
            else if (data == false) {
                alert('You haven\'t taken place yet!!!')
            }
            else { alert(data + ' Out of material!!!') }
        });
    }
</script>
{% endblock content %}